- name: Setup monitoring stack
  hosts: monitoring
  become: yes
  vars:
    prometheus_version: "2.45.0"
    grafana_version: "10.0.0"
    alertmanager_version: "0.25.0"
    node_exporter_version: "1.6.0"

  tasks:
    - name: Create monitoring user
      user:
        name: monitoring
        system: yes
        shell: /bin/bash
        home: /opt/monitoring
        create_home: yes

    - name: Create monitoring directories
      file:
        path: "{{ item }}"
        state: directory
        owner: monitoring
        group: monitoring
        mode: '0755'
      loop:
        - /opt/monitoring/prometheus
        - /opt/monitoring/grafana
        - /opt/monitoring/alertmanager
        - /opt/monitoring/node-exporter
        - /opt/monitoring/data
        - /var/lib/prometheus
        - /var/lib/grafana
        - /var/lib/alertmanager

    - name: Download Prometheus
      get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
        dest: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"

    - name: Extract Prometheus
      unarchive:
        src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
        dest: /tmp
        remote_src: yes

    - name: Install Prometheus binaries
      copy:
        src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        mode: '0755'
        owner: root
        group: root
        remote_src: yes
      loop:
        - prometheus
        - promtool

    - name: Copy Prometheus configuration
      template:
        src: prometheus.yml.j2
        dest: /opt/monitoring/prometheus/prometheus.yml
        owner: monitoring
        group: monitoring
        mode: '0644'
      notify: restart prometheus

    - name: Create Prometheus systemd service
      template:
        src: prometheus.service.j2
        dest: /etc/systemd/system/prometheus.service
      notify:
        - reload systemd
        - restart prometheus

    - name: Download Node Exporter
      get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        dest: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"

    - name: Extract Node Exporter
      unarchive:
        src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        dest: /tmp
        remote_src: yes

    - name: Install Node Exporter binary
      copy:
        src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
        dest: /usr/local/bin/node_exporter
        mode: '0755'
        owner: root
        group: root
        remote_src: yes

    - name: Create Node Exporter systemd service
      template:
        src: node_exporter.service.j2
        dest: /etc/systemd/system/node_exporter.service
      notify:
        - reload systemd
        - restart node_exporter

    - name: Start and enable monitoring services
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - prometheus
        - node_exporter

  handlers:
    - name: reload systemd
      systemd:
        daemon_reload: yes

    - name: restart prometheus
      systemd:
        name: prometheus
        state: restarted

    - name: restart node_exporter
      systemd:
        name: node_exporter
        state: restarted