- name: Setup web servers for Next.js application
  hosts: webservers
  become: yes
  vars:
    app_name: nextjs-auth-app
    app_port: 3000
    nginx_port: 80
    ssl_port: 443
    
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
        cache_valid_time: 86400

    - name: Install required packages
      apt:
        name:
          - curl
          - wget
          - unzip
          - git
          - htop
          - vim
          - ufw
        state: present

    - name: Configure firewall
      ufw:
        rule: allow
        port: "{{ item }}"
      loop:
        - "22"
        - "80"
        - "443"
        - "3000"
        - "9090"
        - "9100"

    - name: Enable firewall
      ufw:
        state: enabled

    - name: Create application user
      user:
        name: "{{ app_name }}"
        system: yes
        shell: /bin/bash
        home: "/opt/{{ app_name }}"
        create_home: yes

    - name: Create application directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ app_name }}"
        group: "{{ app_name }}"
        mode: '0755'
      loop:
        - "/opt/{{ app_name }}/app"
        - "/opt/{{ app_name }}/logs"
        - "/opt/{{ app_name }}/backups"

    - name: Install Node.js
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
        apt-get install -y nodejs
      args:
        creates: /usr/bin/node

    - name: Verify Node.js installation
      command: node --version
      register: node_version
      changed_when: false

    - name: Display Node.js version
      debug:
        msg: "Node.js version: {{ node_version.stdout }}"