global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'blumex-app'
    static_configs:
      - targets: ['blumex-app:80']
        labels:
          group: 'application'

  - job_name: 'blumechain-node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          group: 'blockchain'

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql-exporter:9104']
        labels:
          group: 'database'