apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-auth-app
  namespace: nextjs-auth
  labels:
    app: nextjs-auth-app
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nextjs-auth-app
  template:
    metadata:
      labels:
        app: nextjs-auth-app
        version: v1
    spec:
      containers:
      - name: nextjs-auth-app
        image: ghcr.io/yourusername/nextjs-auth-app:IMAGE_TAG
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: nextjs-auth-config
              key: NODE_ENV
        - name: NEXT_PUBLIC_API_URL
          valueFrom:
            configMapKeyRef:
              name: nextjs-auth-config
              key: NEXT_PUBLIC_API_URL
        - name: JWT_EXPIRES_IN
          valueFrom:
            configMapKeyRef:
              name: nextjs-auth-config
              key: JWT_EXPIRES_IN
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: nextjs-auth-secrets
              key: DATABASE_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: nextjs-auth-secrets
              key: JWT_SECRET
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
      imagePullSecrets:
      - name: ghcr-secret
