apiVersion: v1
kind: Secret
metadata:
  name: nextjs-auth-secrets
  namespace: nextjs-auth
type: Opaque
data:
  # Base64 encoded values - example
  DATABASE_URL: cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAaG9zdDpwb3J0L2RhdGFiYXNl
  JWT_SECRET: eW91ci1zZWNyZXQta2V5LWNoYW5nZS10aGlz
